"""empty message

Revision ID: 1f88bf146e32
Revises: d8554822b51b
Create Date: 2019-03-26 16:04:19.332746

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1f88bf146e32'
down_revision = 'd8554822b51b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sequencing',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sequencing_type', sa.String(), nullable=True),
    sa.Column('machine', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('sequence', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('pileups',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('sequence', sa.String(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('reference_base', sa.String(), nullable=True),
    sa.Column('read_count', sa.Integer(), nullable=True),
    sa.Column('read_results', sa.String(), nullable=True),
    sa.Column('quality', sa.String(), nullable=True),
    sa.Column('sequencing_uuid', postgresql.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['sequencing_uuid'], ['sequencing.uuid'], ),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pileups')
    op.drop_table('sequencing')
    # ### end Alembic commands ###
