"""empty message

Revision ID: 2b0f62d04115
Revises: 1f88bf146e32
Create Date: 2019-03-26 16:08:15.966078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b0f62d04115'
down_revision = '1f88bf146e32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'pileups', ['uuid'])
    op.add_column('sequencing', sa.Column('sequencing_provider', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'sequencing', ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sequencing', type_='unique')
    op.drop_column('sequencing', 'sequencing_provider')
    op.drop_constraint(None, 'pileups', type_='unique')
    # ### end Alembic commands ###
