"""bug testing inserting into tags

Revision ID: 5c2c64f185c9
Revises: 67aee177f3ac
Create Date: 2019-03-25 14:57:17.067884

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5c2c64f185c9'
down_revision = '67aee177f3ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tags_to', 'collection_uuid',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.alter_column('tags_to', 'part_uuid',
               existing_type=postgresql.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tags_to', 'part_uuid',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.alter_column('tags_to', 'collection_uuid',
               existing_type=postgresql.UUID(),
               nullable=False)
    # ### end Alembic commands ###
