"""added names

Revision ID: 62fcac0eea50
Revises: 1c688f268e70
Create Date: 2019-03-25 18:30:06.278401

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '62fcac0eea50'
down_revision = '1c688f268e70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags_parts',
    sa.Column('tags_uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('part_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['part_uuid'], ['parts.uuid'], ),
    sa.ForeignKeyConstraint(['tags_uuid'], ['tags.uuid'], ),
    sa.PrimaryKeyConstraint('tags_uuid', 'part_uuid')
    )
    op.add_column('parts', sa.Column('description', sa.String(), nullable=True))
    op.add_column('parts', sa.Column('full_sequence', sa.String(), nullable=True))
    op.add_column('parts', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parts', 'name')
    op.drop_column('parts', 'full_sequence')
    op.drop_column('parts', 'description')
    op.drop_table('tags_parts')
    # ### end Alembic commands ###
