"""removed virtuals

Revision ID: 67aee177f3ac
Revises: ff59d0a61014
Create Date: 2019-03-25 14:32:42.534256

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '67aee177f3ac'
down_revision = 'ff59d0a61014'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('virtual')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('virtual',
    sa.Column('uuid', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('gene_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('gene_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('virtual_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('vbd', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('resistance', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sequence', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('uuid', name='virtual_pkey'),
    sa.UniqueConstraint('gene_id', name='virtual_gene_id_key'),
    sa.UniqueConstraint('uuid', name='virtual_uuid_key')
    )
    # ### end Alembic commands ###
