"""empty message

Revision ID: 9bc713a0f2d7
Revises: 9993d3b763df
Create Date: 2019-03-26 13:28:33.583094

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9bc713a0f2d7'
down_revision = '9993d3b763df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plates', 'protocol_uuid',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.create_unique_constraint(None, 'protocols', ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'protocols', type_='unique')
    op.alter_column('plates', 'protocol_uuid',
               existing_type=postgresql.UUID(),
               nullable=False)
    # ### end Alembic commands ###
