"""empty message

Revision ID: bd37df7b3bc6
Revises: 2b0f62d04115
Create Date: 2019-03-26 16:14:42.106364

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bd37df7b3bc6'
down_revision = '2b0f62d04115'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sequencing', sa.Column('sample_uuid', postgresql.UUID(), nullable=False))
    op.create_foreign_key(None, 'sequencing', 'samples', ['sample_uuid'], ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sequencing', type_='foreignkey')
    op.drop_column('sequencing', 'sample_uuid')
    # ### end Alembic commands ###
