"""added relationship collection<-parts

Revision ID: ff59d0a61014
Revises: 00e43c68180b
Create Date: 2019-03-25 14:31:47.792022

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ff59d0a61014'
down_revision = '00e43c68180b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'collections', ['uuid'])
    op.add_column('parts', sa.Column('collection_id', postgresql.UUID(), nullable=False))
    op.create_unique_constraint(None, 'parts', ['uuid'])
    op.create_foreign_key(None, 'parts', 'collections', ['collection_id'], ['uuid'])
    op.create_unique_constraint(None, 'tags', ['uuid'])
    op.create_unique_constraint(None, 'virtual', ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'virtual', type_='unique')
    op.drop_constraint(None, 'tags', type_='unique')
    op.drop_constraint(None, 'parts', type_='foreignkey')
    op.drop_constraint(None, 'parts', type_='unique')
    op.drop_column('parts', 'collection_id')
    op.drop_constraint(None, 'collections', type_='unique')
    # ### end Alembic commands ###
