"""empty message

Revision ID: 01d336794a7b
Revises: ad1ec9796d7e
Create Date: 2019-04-09 10:17:06.119570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01d336794a7b'
down_revision = 'ad1ec9796d7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'pipettes', ['uuid'])
    op.add_column('robots', sa.Column('name', sa.String(), nullable=True))
    op.drop_column('robots', 'robot_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('robots', sa.Column('robot_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('robots', 'name')
    op.drop_constraint(None, 'pipettes', type_='unique')
    # ### end Alembic commands ###
