"""empty message

Revision ID: 0dabb8792f1e
Revises: 140bec5a06ff
Create Date: 2019-04-22 16:02:16.446065

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0dabb8792f1e'
down_revision = '140bec5a06ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('distributions_plates')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_table('users')
    op.drop_table('plans')
    op.add_column('parts', sa.Column('ip_check', sa.String(), nullable=True))
    op.add_column('parts', sa.Column('ip_check_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('parts', sa.Column('ip_check_ref', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parts', 'ip_check_ref')
    op.drop_column('parts', 'ip_check_date')
    op.drop_column('parts', 'ip_check')
    op.create_table('plans',
    sa.Column('uuid', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('time_created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('time_updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('plan', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('uuid', name='plans_pkey'),
    sa.UniqueConstraint('uuid', name='plans_uuid_key')
    )
    op.create_table('users',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('id', name='users_id_key')
    )
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.create_table('distributions_plates',
    sa.Column('distribution_uuid', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('plates_uuid', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['distribution_uuid'], ['distributions.uuid'], name='distributions_plates_distribution_uuid_fkey'),
    sa.ForeignKeyConstraint(['plates_uuid'], ['plates.uuid'], name='distributions_plates_plates_uuid_fkey'),
    sa.PrimaryKeyConstraint('distribution_uuid', 'plates_uuid', name='distributions_plates_pkey')
    )
    # ### end Alembic commands ###
