"""empty message

Revision ID: 192f48e16a96
Revises: e050112fab4b
Create Date: 2019-03-28 12:45:20.343352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '192f48e16a96'
down_revision = 'e050112fab4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('new_password_hash', sa.String(length=150), nullable=True))
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_column('users', 'new_password_hash')
    # ### end Alembic commands ###
