"""empty message

Revision ID: 1a2e638b96ff
Revises: 639a48043c6a
Create Date: 2019-04-11 19:33:10.336140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a2e638b96ff'
down_revision = '639a48043c6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seqruns', sa.Column('job', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seqruns', 'job')
    # ### end Alembic commands ###
