"""empty message

Revision ID: 26a3b159776d
Revises: 7f83b55ecde4
Create Date: 2019-04-09 18:00:53.232515

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '26a3b159776d'
down_revision = '7f83b55ecde4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files_organisms',
    sa.Column('files_uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('organisms_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['files_uuid'], ['files.uuid'], ),
    sa.ForeignKeyConstraint(['organisms_uuid'], ['organisms.uuid'], ),
    sa.PrimaryKeyConstraint('files_uuid', 'organisms_uuid')
    )
    op.create_table('files_parts',
    sa.Column('files_uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('parts_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['files_uuid'], ['files.uuid'], ),
    sa.ForeignKeyConstraint(['parts_uuid'], ['parts.uuid'], ),
    sa.PrimaryKeyConstraint('files_uuid', 'parts_uuid')
    )
    op.add_column('fastqs', sa.Column('file_uuid', postgresql.UUID(), nullable=True))
    op.create_foreign_key(None, 'fastqs', 'files', ['file_uuid'], ['uuid'])
    op.alter_column('files', 'file_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('files', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'files', ['uuid'])
    op.add_column('pileups', sa.Column('file_uuid', postgresql.UUID(), nullable=True))
    op.create_foreign_key(None, 'pileups', 'files', ['file_uuid'], ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pileups', type_='foreignkey')
    op.drop_column('pileups', 'file_uuid')
    op.drop_constraint(None, 'files', type_='unique')
    op.alter_column('files', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('files', 'file_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'fastqs', type_='foreignkey')
    op.drop_column('fastqs', 'file_uuid')
    op.drop_table('files_parts')
    op.drop_table('files_organisms')
    # ### end Alembic commands ###
