"""removed location, added breadcrumb

Revision ID: 392769156199
Revises: 6fe6f20aa545
Create Date: 2019-04-09 10:46:42.044508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '392769156199'
down_revision = '6fe6f20aa545'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plates', 'location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plates', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
