"""empty message

Revision ID: 445b94f3a7ab
Revises: a5d8968018e4
Create Date: 2019-04-01 16:52:36.772282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '445b94f3a7ab'
down_revision = 'a5d8968018e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'fastqs', ['uuid'])
    op.create_unique_constraint(None, 'pileups', ['uuid'])
    op.create_unique_constraint(None, 'seqruns', ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'seqruns', type_='unique')
    op.drop_constraint(None, 'pileups', type_='unique')
    op.drop_constraint(None, 'fastqs', type_='unique')
    # ### end Alembic commands ###
