"""empty message

Revision ID: 4ff542d1b136
Revises: 192f48e16a96
Create Date: 2019-03-28 12:46:41.522725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ff542d1b136'
down_revision = '192f48e16a96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=150), nullable=True))
    op.drop_column('users', 'new_password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('new_password_hash', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
