"""empty message

Revision ID: 5fb62d568543
Revises: 9f4ae570ccd5
Create Date: 2019-04-05 15:38:30.747611

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5fb62d568543'
down_revision = '9f4ae570ccd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('containers',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('parent_uuid', postgresql.UUID(), nullable=True),
    sa.Column('child_locations', sa.JSON(), nullable=True),
    sa.Column('location', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['parent_uuid'], ['containers.uuid'], ),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('organisms',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('organism_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    op.drop_column('parts', 'resistance')
    op.add_column('plates', sa.Column('container_uuid', postgresql.UUID(), nullable=True))
    op.add_column('plates', sa.Column('location', sa.String(), nullable=True))
    op.create_foreign_key(None, 'plates', 'containers', ['container_uuid'], ['uuid'])
    op.drop_column('plates', 'breadcrumb')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plates', sa.Column('breadcrumb', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'plates', type_='foreignkey')
    op.drop_column('plates', 'location')
    op.drop_column('plates', 'container_uuid')
    op.add_column('parts', sa.Column('resistance', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('organisms')
    op.drop_table('containers')
    # ### end Alembic commands ###
