"""added name and machine id

Revision ID: 639a48043c6a
Revises: 730b7a59f66d
Create Date: 2019-04-11 15:46:49.197548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '639a48043c6a'
down_revision = '730b7a59f66d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seqruns', sa.Column('machine_id', sa.String(), nullable=True))
    op.add_column('seqruns', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seqruns', 'name')
    op.drop_column('seqruns', 'machine_id')
    # ### end Alembic commands ###
