"""empty message

Revision ID: 695dddbef8de
Revises: 4637cc68a77f
Create Date: 2019-04-05 16:20:20.020158

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '695dddbef8de'
down_revision = '4637cc68a77f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('containers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('containers',
    sa.Column('uuid', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('uuid', name='containers_pkey'),
    sa.UniqueConstraint('uuid', name='containers_uuid_key')
    )
    # ### end Alembic commands ###
