"""empty message

Revision ID: 6ddedd124803
Revises: c7f3c56f2b8c
Create Date: 2019-03-27 10:10:20.123692

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6ddedd124803'
down_revision = 'c7f3c56f2b8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('affiliation', sa.String(), nullable=True),
    sa.Column('orcid', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    op.create_unique_constraint(None, 'collections', ['uuid'])
    op.create_unique_constraint(None, 'parts', ['uuid'])
    op.create_unique_constraint(None, 'pileups', ['uuid'])
    op.create_unique_constraint(None, 'plates', ['uuid'])
    op.create_unique_constraint(None, 'protocols', ['uuid'])
    op.create_unique_constraint(None, 'robots', ['uuid'])
    op.create_unique_constraint(None, 'samples', ['uuid'])
    op.create_unique_constraint(None, 'sequencing', ['uuid'])
    op.create_unique_constraint(None, 'tags', ['uuid'])
    op.create_unique_constraint(None, 'wells', ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wells', type_='unique')
    op.drop_constraint(None, 'tags', type_='unique')
    op.drop_constraint(None, 'sequencing', type_='unique')
    op.drop_constraint(None, 'samples', type_='unique')
    op.drop_constraint(None, 'robots', type_='unique')
    op.drop_constraint(None, 'protocols', type_='unique')
    op.drop_constraint(None, 'plates', type_='unique')
    op.drop_constraint(None, 'pileups', type_='unique')
    op.drop_constraint(None, 'parts', type_='unique')
    op.drop_constraint(None, 'collections', type_='unique')
    op.drop_table('authors')
    # ### end Alembic commands ###
