"""empty message

Revision ID: 6fe6f20aa545
Revises: 7cb63128edea
Create Date: 2019-04-09 10:43:48.441730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fe6f20aa545'
down_revision = '7cb63128edea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plates', sa.Column('notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plates', 'notes')
    # ### end Alembic commands ###
