"""empty message

Revision ID: 730b7a59f66d
Revises: e96ea2e54df5
Create Date: 2019-04-10 18:38:22.107162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '730b7a59f66d'
down_revision = 'e96ea2e54df5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'distributions', ['uuid'])
    op.create_unique_constraint(None, 'plans', ['uuid'])
    op.add_column('samples', sa.Column('evidence', sa.String(), nullable=True))
    op.add_column('samples', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('samples', 'status')
    op.drop_column('samples', 'evidence')
    op.drop_constraint(None, 'plans', type_='unique')
    op.drop_constraint(None, 'distributions', type_='unique')
    # ### end Alembic commands ###
