"""empty message

Revision ID: 7ba659111299
Revises: 695dddbef8de
Create Date: 2019-04-08 12:53:50.199383

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7ba659111299'
down_revision = '695dddbef8de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags_authors',
    sa.Column('tags_uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('author_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['author_uuid'], ['authors.uuid'], ),
    sa.ForeignKeyConstraint(['tags_uuid'], ['tags.uuid'], ),
    sa.PrimaryKeyConstraint('tags_uuid', 'author_uuid')
    )
    op.create_table('tags_organisms',
    sa.Column('tags_uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('organism_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['organism_uuid'], ['organisms.uuid'], ),
    sa.ForeignKeyConstraint(['tags_uuid'], ['tags.uuid'], ),
    sa.PrimaryKeyConstraint('tags_uuid', 'organism_uuid')
    )
    op.add_column('organisms', sa.Column('genotype', sa.String(), nullable=True))
    op.drop_column('organisms', 'organism_id')
    op.add_column('protocols', sa.Column('robot_uuid', postgresql.UUID(), nullable=True))
    op.create_foreign_key(None, 'protocols', 'robots', ['robot_uuid'], ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'protocols', type_='foreignkey')
    op.drop_column('protocols', 'robot_uuid')
    op.add_column('organisms', sa.Column('organism_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('organisms', 'genotype')
    op.drop_table('tags_organisms')
    op.drop_table('tags_authors')
    # ### end Alembic commands ###
