"""empty message

Revision ID: 7cb63128edea
Revises: 01d336794a7b
Create Date: 2019-04-09 10:40:05.937936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cb63128edea'
down_revision = '01d336794a7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plates', sa.Column('breadcrumb', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plates', 'breadcrumb')
    # ### end Alembic commands ###
