"""empty message

Revision ID: 9f4ae570ccd5
Revises: d3e8b6eeba79
Create Date: 2019-04-04 16:38:27.136666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f4ae570ccd5'
down_revision = 'd3e8b6eeba79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parts', sa.Column('translation', sa.String(), nullable=True))
    op.add_column('protocols', sa.Column('protocol_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('protocols', 'protocol_type')
    op.drop_column('parts', 'translation')
    # ### end Alembic commands ###
