"""empty message

Revision ID: a5d58349ea7d
Revises: 6ddedd124803
Create Date: 2019-03-27 10:12:52.604247

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a5d58349ea7d'
down_revision = '6ddedd124803'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'authors', ['uuid'])
    op.add_column('parts', sa.Column('author_uuid', postgresql.UUID(), nullable=False))
    op.create_foreign_key(None, 'parts', 'authors', ['author_uuid'], ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'parts', type_='foreignkey')
    op.drop_column('parts', 'author_uuid')
    op.drop_constraint(None, 'authors', type_='unique')
    # ### end Alembic commands ###
