"""Added fastq,seqrun,pileup tables

Revision ID: a5d8968018e4
Revises: bd7db7a3e3b2
Create Date: 2019-04-01 16:36:36.816334

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a5d8968018e4'
down_revision = 'bd7db7a3e3b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seqruns',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('sequencing_type', sa.String(), nullable=True),
    sa.Column('machine', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('fastqs',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('seqrun_uuid', postgresql.UUID(), nullable=False),
    sa.Column('fastq_link', sa.String(), nullable=True),
    sa.Column('raw_link', sa.String(), nullable=True),
    sa.Column('index_for', sa.String(), nullable=True),
    sa.Column('index_rev', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['seqrun_uuid'], ['seqruns.uuid'], ),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('pileups',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('full_search_sequence', sa.String(), nullable=True),
    sa.Column('target_sequence', sa.String(), nullable=True),
    sa.Column('pileup_link', sa.String(), nullable=True),
    sa.Column('fastq_uuid', postgresql.UUID(), nullable=False),
    sa.Column('sample_uuid', postgresql.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['fastq_uuid'], ['fastqs.uuid'], ),
    sa.ForeignKeyConstraint(['sample_uuid'], ['samples.uuid'], ),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pileups')
    op.drop_table('fastqs')
    op.drop_table('seqruns')
    # ### end Alembic commands ###
