"""empty message

Revision ID: ad1ec9796d7e
Revises: 7ba659111299
Create Date: 2019-04-09 10:15:49.729263

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ad1ec9796d7e'
down_revision = '7ba659111299'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipettes',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('pipette_type', sa.String(), nullable=True),
    sa.Column('mount_side', sa.String(), nullable=True),
    sa.Column('robot_uuid', postgresql.UUID(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['robot_uuid'], ['robots.uuid'], ),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    op.drop_constraint('robots_left_10_key', 'robots', type_='unique')
    op.drop_constraint('robots_right_300_key', 'robots', type_='unique')
    op.drop_column('robots', 'left_10')
    op.drop_column('robots', 'right_300')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('robots', sa.Column('right_300', postgresql.UUID(), autoincrement=False, nullable=False))
    op.add_column('robots', sa.Column('left_10', postgresql.UUID(), autoincrement=False, nullable=False))
    op.create_unique_constraint('robots_right_300_key', 'robots', ['right_300'])
    op.create_unique_constraint('robots_left_10_key', 'robots', ['left_10'])
    op.drop_table('pipettes')
    # ### end Alembic commands ###
