"""Removed sequencing files and pileups

Revision ID: bd7db7a3e3b2
Revises: 4ff542d1b136
Create Date: 2019-04-01 15:14:49.294622

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bd7db7a3e3b2'
down_revision = '4ff542d1b136'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pileups')
    op.drop_table('sequencing')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sequencing',
    sa.Column('uuid', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('time_created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('time_updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('sequencing_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sequencing_notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sequencing_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('machine', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sequencing_provider', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sequence', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sample_uuid', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['sample_uuid'], ['samples.uuid'], name='sequencing_sample_uuid_fkey'),
    sa.PrimaryKeyConstraint('uuid', name='sequencing_pkey'),
    sa.UniqueConstraint('uuid', name='sequencing_uuid_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('pileups',
    sa.Column('uuid', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('sequence', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reference_base', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('read_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('read_results', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('quality', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sequencing_uuid', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['sequencing_uuid'], ['sequencing.uuid'], name='pileups_sequencing_uuid_fkey'),
    sa.PrimaryKeyConstraint('uuid', name='pileups_pkey'),
    sa.UniqueConstraint('uuid', name='pileups_uuid_key')
    )
    # ### end Alembic commands ###
