"""empty message

Revision ID: d3e8b6eeba79
Revises: 445b94f3a7ab
Create Date: 2019-04-02 10:11:33.528945

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd3e8b6eeba79'
down_revision = '445b94f3a7ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pileup_fastq',
    sa.Column('pileup_uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('fastq_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['fastq_uuid'], ['fastqs.uuid'], ),
    sa.ForeignKeyConstraint(['pileup_uuid'], ['pileups.uuid'], ),
    sa.PrimaryKeyConstraint('pileup_uuid', 'fastq_uuid')
    )
    op.drop_constraint('pileups_fastq_uuid_fkey', 'pileups', type_='foreignkey')
    op.drop_column('pileups', 'fastq_uuid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pileups', sa.Column('fastq_uuid', postgresql.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('pileups_fastq_uuid_fkey', 'pileups', 'fastqs', ['fastq_uuid'], ['uuid'])
    op.drop_table('pileup_fastq')
    # ### end Alembic commands ###
