"""empty message

Revision ID: d72eba929345
Revises: 26a3b159776d
Create Date: 2019-04-09 18:40:58.401463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd72eba929345'
down_revision = '26a3b159776d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fastqs', sa.Column('name', sa.String(), nullable=True))
    op.drop_column('fastqs', 'raw_link')
    op.drop_column('fastqs', 'fastq_link')
    op.drop_column('pileups', 'pileup_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pileups', sa.Column('pileup_link', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('fastqs', sa.Column('fastq_link', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('fastqs', sa.Column('raw_link', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('fastqs', 'name')
    # ### end Alembic commands ###
