"""empty message

Revision ID: e4da00925137
Revises: 0dabb8792f1e
Create Date: 2019-04-22 16:02:43.077018

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e4da00925137'
down_revision = '0dabb8792f1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('distributions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('distributions',
    sa.Column('uuid', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('time_created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('time_updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('collection_uuid', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['collection_uuid'], ['collections.uuid'], name='distributions_collection_uuid_fkey'),
    sa.PrimaryKeyConstraint('uuid', name='distributions_pkey'),
    sa.UniqueConstraint('uuid', name='distributions_uuid_key')
    )
    # ### end Alembic commands ###
