"""empty message

Revision ID: e96ea2e54df5
Revises: d72eba929345
Create Date: 2019-04-10 18:31:03.590338

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e96ea2e54df5'
down_revision = 'd72eba929345'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('plan', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('distributions',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('collection_uuid', postgresql.UUID(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['collection_uuid'], ['collections.uuid'], ),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('distributions_plates',
    sa.Column('distribution_uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('plates_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['distribution_uuid'], ['distributions.uuid'], ),
    sa.ForeignKeyConstraint(['plates_uuid'], ['plates.uuid'], ),
    sa.PrimaryKeyConstraint('distribution_uuid', 'plates_uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('distributions_plates')
    op.drop_table('distributions')
    op.drop_table('plans')
    # ### end Alembic commands ###
